name: build-wireshark-windows

on:
  workflow_call:

  push:
    branches: [
      test_build_wireshark_source
    ]

jobs:
  build_windows:
    runs-on: windows-latest
    env:
      PLATFORM: x64

    steps:
      - name: Install Qt6
        uses: jurplel/install-qt-action@v4      
        with:
          version: '6.5.2'
          dir: $GITHUB_WORKSPACE
        
      - run: ls -al $GITHUB_WORKSPACE

      # - name: Install Flex 
      #   run: choco install winflexbison3 -y

      # - name: Checkout Wireshark source
      #   uses: actions/checkout@v4
      #   with:
      #     repository: wireshark/wireshark
      #     ref: v3.6.24
      #     path: wireshark
 
      # - name: Make build directory
      #   working-directory: wireshark
      #   run: mkdir build

      # - name: Configure cmake
      #   working-directory: wireshark/build
      #   run: |
      #     $env:WIRESHARK_BASE_DIR = $env:GITHUB_WORKSPACE
      #     $env:WIRESHARK_QT6_PREFIX_PATH = $env:RUNNER_WORKSPACE\Qt\6.5.2\msvc2019_64
      #     cmake -G "Visual Studio 17 2022" -A x64 ..

      # - name: Build and install wireshark
      #   working-directory: wireshark/build
      #   run: |
      #     cmake --build .
      #     cmake --install .

      # - name: Save built binaries to cache
      #   id: cache-bin
      #   uses: actions/cache/save@v4
      #   with:
      #     key: ubuntu-20_04-cache
      #     path: |
      #       ./wireshark_artifacts/**
      #       ./wireshark/build/config.h
