name: build-wireshark-windows

on:
  workflow_call:

  # push:
  #   branches: [
  #     test_build_wireshark_source
  #   ]

jobs:
  build_windows:
    runs-on: windows-latest
    env:
      PLATFORM: x64

    steps:
      - name: Install Qt 5
        uses: jurplel/install-qt-action@v4      
        with:
          version: '5.15.2'
          dir: ${{ github.workspace }}
        
      - name: Install Flex 
        run: choco install winflexbison3 -y

      - name: Checkout Wireshark source
        uses: actions/checkout@v4
        with:
          repository: wireshark/wireshark
          ref: v3.6.24
          path: wireshark
 
      - name: Make build directory
        working-directory: wireshark
        run: mkdir build

      - name: Configure cmake
        working-directory: wireshark/build
        run: |
          $env:WIRESHARK_BASE_DIR = $env:GITHUB_WORKSPACE
          cmake -G "Visual Studio 17 2022" -A x64 -DCMAKE_PREFIX_PATH="${env:GITHUB_WORKSPACE}\Qt\5.15.2\msvc2019_64" ..

      - name: Build wireshark
        working-directory: wireshark/build
        run: cmake --build . --config Release

      - name: install wireshark
        working-directory: wireshark/build
        run: |
          mkdir $env:GITHUB_WORKSPACE\wireshark_artifacts
          cmake --install . --prefix $env:GITHUB_WORKSPACE\wireshark_artifacts --config Release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: $env:GITHUB_WORKSPACE/wireshark_artifacts/**

      - name: Save built binaries to cache
        id: cache-bin
        uses: actions/cache/save@v4
        with:
          key: windows-cache
          path: |
            ./wireshark_artifacts/**
            ./wireshark/build/config.h
