name: build-jaus-plugin

on:
  workflow_call:

  push:
    branches: [
      test_build_wireshark_source
    ]

jobs:
  build_ubuntu-20_04:
    runs-on: ubuntu-20.04

    steps:
      - name: Restore built binaries from cache
        id: cache-bin
        uses: actions/cache/restore@v4
        with:
          key: ubuntu-20_04-cache
          fail-on-cache-miss: true
          path: |
            ./wireshark_artifacts/**
            ./wireshark/build/config.h
          

      - name: List wireshark_artifacts
        shell: bash
        run: ls $GITHUB_WORKSPACE

      - name: Checkout plugin code
        uses: actions/checkout@v4
        with:
          path: jaustoolset

      - name: List wireshark_artifacts
        shell: bash
        run: ls $GITHUB_WORKSPACE
        
      - name: Install dependencies
        shell: bash
        run: |
          sudo add-apt-repository universe
          sudo apt-get update
          sudo apt-get install -y libxml2-dev

      - name: Create build folder
        working-directory: jaustoolset/wiresharkPlugin/packet-jaus/src/Wireshark-3.2.x
        shell: bash
        run: mkdir build

      - name: Configure plugin
        working-directory: jaustoolset/wiresharkPlugin/packet-jaus/src/Wireshark-3.2.x/build
        shell: bash
        run: cmake -DCMAKE_PREFIX_PATH=$GITHUB_WORKSPACE/wireshark_artifacts ..
      
      # # - name: Upload CMakeCache
      # #   uses: actions/upload-artifact@v3
      # #   with:
      # #     name: plugin_build_artifacts
      # #     path: wiresharkPlugin/packet-jaus/src/Wireshark-3.2.x/build

      - name: Copy config.h
        working-directory: jaustoolset/wiresharkPlugin/packet-jaus/src/Wireshark-3.2.x/build
        shell: bash
        run: cp $GITHUB_WORKSPACE/wireshark/build/config.h ..

      - name: Build plugin
        working-directory: jaustoolset/wiresharkPlugin/packet-jaus/src/Wireshark-3.2.x/build
        shell: bash
        run: cmake --build .
